(MODULES-6166) virtual_directory requires sitename
 - Validate blocks on a type do not run when `puppet resource`
   executes, so mandatory parameters are not enforced when using
   `puppet resource` (aside from the namevar)

 - Previously `puppet resource iis_virtual_directory foo ensure=present`
   would report success even though it failed, when `sitename` was
   left unspecified:

bundle exec puppet resource iis_virtual_directory foo physicalpath=c:/foo ensure=present --modulepath .\spec\fixtures\modules\
Notice: /Iis_virtual_directory[foo]/ensure: created
iis_virtual_directory { 'foo':
  ensure => 'absent',
}

Asking for iis_virtual_directory instances yields no results:

bundle exec puppet resource iis_virtual_directory --modulepath .\spec\fixtures\modules\

 - This change introduces a hard failure when sitename is not specified

bundle exec puppet resource iis_virtual_directory foo physicalpath=c:/foo ensure=present --modulepath .\spec\fixtures\modules\
Error: sitename is a required parameter
Error: /Iis_virtual_directory[foo]/ensure: change from 'absent' to 'present' failed: sitename is a required parameter
iis_virtual_directory { 'foo':
  ensure => 'absent',
}

 - This is not necessary to perform on the `destroy` method as
   00096d2541bbab4f41777b9b447d919203c84aa2 changed destroy to use
   @property_hash (as populated from the system) rather than the
   previous usage of @resource, which could be missing :sitename.

   During creation, @resource[:sitename] must be used as there is no
   existing state to read from the system